networks:
    employee-network:
        driver: bridge
volumes:
    employee-mssql-data:

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: employee-mssql
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Password.123"
        ports:
            - "1433:1433"
        volumes:
            - employee-mssql-data:/var/opt/mssql
        networks:
            - employee-network

    employee-api:
        image: employee-api
        container_name: employee-api
        environment:
            DB_PASSWORD: "Password.123"
            DB_HOST: "employee-mssql"
            DB_PORT: "1433"
            DB_USER: "sa"
        ports:
            - "8081:8081"
        depends_on:
            - mssql
        networks:
            - employee-network