server:
    port: 8081

spring:
    datasource:
        url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=master;encrypt=false
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        open-in-view: false