apiVersion: v1
kind: Pod
metadata:
    name: employee-api
    labels:
        app: employee-api
spec:
    containers:
        -   name: employee-api
            image: employee-api
            imagePullPolicy: IfNotPresent
            ports:
                -   containerPort: 8081
            env:
                -   name: DB_HOST
                    value: "employee-mssql"
                -   name: DB_PORT
                    value: "1433"
                -   name: DB_USER
                    value: "sa"
                -   name: DB_PASSWORD
                    value: "Password.123"
---
apiVersion: v1
kind: Service
metadata:
    name: employee-api
spec:
    selector:
        app: employee-api
    ports:
        -   protocol: TCP
            port: 8081
            targetPort: 8081
            nodePort: 31434
    type: NodePort # Or LoadBalancer if in cloud