apiVersion: v1
kind: Pod
metadata:
    name: employee-mssql
    labels:
        app: employee-mssql
spec:
    containers:
        -   name: mssql
            image: mcr.microsoft.com/mssql/server:2022-latest
            ports:
                -   containerPort: 1433
            env:
                -   name: ACCEPT_EULA
                    value: "Y"
                -   name: SA_PASSWORD
                    value: "Password.123"
            volumeMounts:
                -   name: employee-mssql-data
                    mountPath: /var/opt/mssql
    volumes:
        -   name: employee-mssql-data
            emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
    name: employee-mssql
spec:
    selector:
        app: employee-mssql
    ports:
        -   protocol: TCP
            port: 1433
            targetPort: 1433
            nodePort: 31433
    type: NodePort # Or LoadBalancer if in cloud